<<<<<<< HEAD
<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
=======
=======
import '@/app/ui/global.css'; 
>>>>>>> Nicholas_dev

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; 
}) {
  return (
    <html lang="en">
      <body className="bg-customBg">{children}</body>
    </html>
  )
<<<<<<< HEAD
>>>>>>> origin/Nicholas_dev
=======
>>>>>>> Nicholas_dev
}
