import '@/app/ui/global.css'; 
import Header from "@/app/ui/header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-customBg">{children}</body>
    </html>
  );
}